name: wsstat
adopt-info: wsstat
license: MIT
summary: wsstat is a websocket endpoint monitoring tool
description: |
  wsstat provides a simple and easy to use tool to check the status and connection stats of a WebSocket endpoint.

  Usage: wsstat wss://foo.example.com

grade: stable
confinement: strict
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  wsstat:
    command: bin/wsstat
    plugs: [network, home]

parts:
  go-deps:
    plugin: nil
    source: https://go.dev/dl/go1.25.1.linux-amd64.tar.gz
    source-type: tar
    override-build: |
      install -d "${CRAFT_PART_INSTALL}/usr/local/go"
      cp -a "${CRAFT_PART_SRC}/." "${CRAFT_PART_INSTALL}/usr/local/go/"
    stage:
      - usr/local/go/**
    prime: []
    # TODO: consider ignoring the testdata files
    #lint:
    #  ignore:
    #    library:
    #      - usr/local/go/src/debug/elf/testdata/libtiffxx.so_

  wsstat:
    plugin: go
    after: [go-deps]
    source: .
    build-packages:
      - git
    build-environment:
      - PATH: "${CRAFT_STAGE}/usr/local/go/bin:${PATH}"
      - GOPROXY: "https://proxy.golang.org,direct"
      - GOSUMDB: "sum.golang.org"
    override-pull: |
      craftctl default
      if git describe --tags --abbrev=7 >/tmp/wsstat.version 2>/dev/null; then
        craftctl set version="$(cat /tmp/wsstat.version)"
      else
        craftctl set version="$(git rev-parse --short HEAD)"
      fi
    override-build: |
      CGO_ENABLED=0 go build -ldflags "-X main.version=$(craftctl get version)" -o "${CRAFT_PART_INSTALL}/bin/wsstat" ./cmd/wsstat
